controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

about_us:
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    path: /about-us
    defaults:
        template: 'page/about_us.html.twig'